theme = "danrot"

[editor]
auto-format = false
line-number = "relative"
mouse = false
rulers = [121]
text-width = 120

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
git-global = false
git-ignore = false
hidden = false

[editor.indent-guides]
render = true
character = "‚ñè"

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "version-control", "position", "position-percentage", "file-encoding"]
mode.insert = "INSERT"
mode.normal = "NORMAL"
mode.select = "SELECT"
